/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital_is;

import com.algorithms.BinarySearch;
import com.algorithms.SelectionSort;
import com.dialogs.ExitingDialogBox;
import com.dialogs.LogoutDialogBox;
import com.dialogs.MessageDialogBox;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abc
 */
public class HospitalInfo extends javax.swing.JFrame {
    TablePage tablePage;
    FormPage formPage;
    AboutUsPage aboutUsPage;
    
    private SimpleDateFormat dayFormat, dateFormat, timeFormat;
    private String day, date, time;
    
    /**
     * Creates new form HospitalInfo
     */
    public HospitalInfo() {
        initComponents(); 
        tablePage = new TablePage(this);
        formPage = new FormPage(this);
        aboutUsPage = new AboutUsPage(this);
        ImageIcon applicationIcon = new ImageIcon("src/com/icons/application_hospital_icon.png");
        this.setIconImage(applicationIcon.getImage());
        
        setCalendar();
    }
    
    public void setCalendar() {
        dayFormat = new SimpleDateFormat("EEEE");
        dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
        timeFormat = new SimpleDateFormat("hh:mm a");
        day =  dayFormat.format(Calendar.getInstance().getTime());
        date = dateFormat.format(Calendar.getInstance().getTime());
        String today_calendar = String.format("%s  %s", day, date);
        dateLabel.setText(today_calendar); 
    }

    public TablePage getTablePage() {
        return tablePage;
    }

    public FormPage getFormPage() {
        return formPage;
    }

    public AboutUsPage getAboutUsPage() {
        return aboutUsPage;
    }

    public JLabel getHospitalNumberLabel() {
        return hospitalNumberLabel;
    }
    
    public void enableTypingNumberKeyOnly(KeyEvent event) {
        char userTypedCharacter = event.getKeyChar();
        if(!(Character.isDigit(userTypedCharacter)) || (userTypedCharacter == KeyEvent.VK_BACK_SPACE)
                || (userTypedCharacter == KeyEvent.VK_DELETE)) {
            event.consume();
        }
    }
    
    public void addSortedData() {
        DefaultTableModel tableModel = (DefaultTableModel) tablePage.getHospitalInfoTable().getModel();
        tableModel.setRowCount(0); 
        for(HospitalData data : tablePage.getHospitalDatas()) {
            String values[] = {data.getHospitalName(), data.getAddress(), String.valueOf(data.getTelephoneNumber()), 
                data.getHospitalCategory(), String.valueOf(data.getAdmittedPrice()), data.getHealthInsurence()};
            tableModel.addRow(values); 
        }
    }
    
    public String getHospitalSearchInformationAtIndex(int index) {
        String name = tablePage.getHospitalDatas().get(index).getHospitalName();
        String address = tablePage.getHospitalDatas().get(index).getAddress();
        long telephone = tablePage.getHospitalDatas().get(index).getTelephoneNumber();
        String category = tablePage.getHospitalDatas().get(index).getHospitalCategory();
        double price = tablePage.getHospitalDatas().get(index).getAdmittedPrice();
        String insurance = tablePage.getHospitalDatas().get(index).getHealthInsurence();
        String message = "--------------------Hospital Information--------------------\n"
                + "Name: " + name +"\n"
                + "Address: " + address +"\n"
                + "Telephone: " + telephone +"\n"
                + "category: " + category +"\n"
                + "Price: " + price +"\n" 
                + "Insurance: " + insurance +"\n"; 
        return message;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchByHospitalCategoryButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        homePageLabel = new javax.swing.JLabel();
        formPageLabel = new javax.swing.JLabel();
        tablePageLabel = new javax.swing.JLabel();
        aboutUsPageLabel = new javax.swing.JLabel();
        logOutLabel = new javax.swing.JLabel();
        searchByHospitalNameField = new javax.swing.JTextField();
        searchIconLabel = new javax.swing.JLabel();
        dashboardOne = new javax.swing.JPanel();
        dashboardTitlePanelOne = new javax.swing.JPanel();
        dashboardTitleLabelOne = new javax.swing.JLabel();
        hospitalNumberLabel = new javax.swing.JLabel();
        dashboardTwo = new javax.swing.JPanel();
        dashboardTitlePanelTwo = new javax.swing.JPanel();
        dashboardTitleLabelTwo = new javax.swing.JLabel();
        searchByPriceField = new javax.swing.JTextField();
        searchByPriceButton = new javax.swing.JLabel();
        rupeesLabel = new javax.swing.JLabel();
        dashboardFour = new javax.swing.JPanel();
        dashboardTitlePanelFour = new javax.swing.JPanel();
        dashboardTitleLabelFour = new javax.swing.JLabel();
        applicationCloseButton = new javax.swing.JButton();
        dashboardThree = new javax.swing.JPanel();
        dashboardTitlePanelThree = new javax.swing.JPanel();
        dashboardTitleLabelThree = new javax.swing.JLabel();
        searchByGovernment = new javax.swing.JRadioButton();
        searchByPrivate = new javax.swing.JRadioButton();
        searchByCategoryButton = new javax.swing.JLabel();
        searchByNameButton = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(56, 48, 76));

        sideBarPanel.setBackground(new java.awt.Color(32, 26, 49));

        titlePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 153, 255)));
        titlePanel.setOpaque(false);

        titleLabel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/hospital.png"))); // NOI18N
        titleLabel.setText("Hospital IS");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titleLabel)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        homePageLabel.setBackground(new java.awt.Color(56, 48, 76));
        homePageLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        homePageLabel.setForeground(new java.awt.Color(13, 245, 227));
        homePageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homePageLabel.setText("Home");
        homePageLabel.setOpaque(true);
        homePageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homePageLabelMouseExited(evt);
            }
        });

        formPageLabel.setBackground(new java.awt.Color(32, 26, 49));
        formPageLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        formPageLabel.setForeground(new java.awt.Color(255, 255, 255));
        formPageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPageLabel.setText("Form");
        formPageLabel.setOpaque(true);
        formPageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formPageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formPageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formPageLabelMouseExited(evt);
            }
        });

        tablePageLabel.setBackground(new java.awt.Color(32, 26, 49));
        tablePageLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        tablePageLabel.setForeground(new java.awt.Color(255, 255, 255));
        tablePageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tablePageLabel.setText("Table");
        tablePageLabel.setOpaque(true);
        tablePageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablePageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablePageLabelMouseExited(evt);
            }
        });

        aboutUsPageLabel.setBackground(new java.awt.Color(32, 26, 49));
        aboutUsPageLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        aboutUsPageLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutUsPageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutUsPageLabel.setText("About Us");
        aboutUsPageLabel.setOpaque(true);
        aboutUsPageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsPageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutUsPageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutUsPageLabelMouseExited(evt);
            }
        });

        logOutLabel.setBackground(new java.awt.Color(32, 26, 49));
        logOutLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        logOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutLabel.setText("Log Out");
        logOutLabel.setOpaque(true);
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homePageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablePageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aboutUsPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(homePageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(formPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(tablePageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(aboutUsPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(logOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        searchByHospitalNameField.setBackground(new java.awt.Color(56, 48, 76));
        searchByHospitalNameField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        searchByHospitalNameField.setForeground(new java.awt.Color(255, 255, 255));
        searchByHospitalNameField.setText("Search");
        searchByHospitalNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        searchByHospitalNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByHospitalNameFieldMouseClicked(evt);
            }
        });

        searchIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/search.png"))); // NOI18N

        dashboardOne.setBackground(new java.awt.Color(32, 26, 49));

        dashboardTitlePanelOne.setBackground(new java.awt.Color(98, 76, 249));

        dashboardTitleLabelOne.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dashboardTitleLabelOne.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTitleLabelOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardTitleLabelOne.setText("Number of Hospital");

        javax.swing.GroupLayout dashboardTitlePanelOneLayout = new javax.swing.GroupLayout(dashboardTitlePanelOne);
        dashboardTitlePanelOne.setLayout(dashboardTitlePanelOneLayout);
        dashboardTitlePanelOneLayout.setHorizontalGroup(
            dashboardTitlePanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLabelOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardTitlePanelOneLayout.setVerticalGroup(
            dashboardTitlePanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardTitlePanelOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardTitleLabelOne, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        hospitalNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        hospitalNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        hospitalNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalNumberLabel.setText("0");

        javax.swing.GroupLayout dashboardOneLayout = new javax.swing.GroupLayout(dashboardOne);
        dashboardOne.setLayout(dashboardOneLayout);
        dashboardOneLayout.setHorizontalGroup(
            dashboardOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitlePanelOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hospitalNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashboardOneLayout.setVerticalGroup(
            dashboardOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardOneLayout.createSequentialGroup()
                .addComponent(dashboardTitlePanelOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hospitalNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        dashboardTwo.setBackground(new java.awt.Color(32, 26, 49));

        dashboardTitlePanelTwo.setBackground(new java.awt.Color(98, 76, 249));

        dashboardTitleLabelTwo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dashboardTitleLabelTwo.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTitleLabelTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardTitleLabelTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/search.png"))); // NOI18N
        dashboardTitleLabelTwo.setText("Search By Admitted Price");
        dashboardTitleLabelTwo.setToolTipText("");

        javax.swing.GroupLayout dashboardTitlePanelTwoLayout = new javax.swing.GroupLayout(dashboardTitlePanelTwo);
        dashboardTitlePanelTwo.setLayout(dashboardTitlePanelTwoLayout);
        dashboardTitlePanelTwoLayout.setHorizontalGroup(
            dashboardTitlePanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLabelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardTitlePanelTwoLayout.setVerticalGroup(
            dashboardTitlePanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTitlePanelTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardTitleLabelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        searchByPriceField.setBackground(new java.awt.Color(56, 48, 76));
        searchByPriceField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        searchByPriceField.setForeground(new java.awt.Color(255, 255, 255));
        searchByPriceField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        searchByPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchByPriceFieldKeyTyped(evt);
            }
        });

        searchByPriceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/go.png"))); // NOI18N
        searchByPriceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByPriceButtonMouseClicked(evt);
            }
        });

        rupeesLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rupeesLabel.setForeground(new java.awt.Color(255, 255, 255));
        rupeesLabel.setText("Rs.");

        javax.swing.GroupLayout dashboardTwoLayout = new javax.swing.GroupLayout(dashboardTwo);
        dashboardTwo.setLayout(dashboardTwoLayout);
        dashboardTwoLayout.setHorizontalGroup(
            dashboardTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitlePanelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardTwoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchByPriceButton)
                .addGap(126, 126, 126))
            .addGroup(dashboardTwoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(rupeesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchByPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardTwoLayout.setVerticalGroup(
            dashboardTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTwoLayout.createSequentialGroup()
                .addComponent(dashboardTitlePanelTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dashboardTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rupeesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchByPriceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dashboardFour.setBackground(new java.awt.Color(32, 26, 49));

        dashboardTitlePanelFour.setBackground(new java.awt.Color(98, 76, 249));

        dashboardTitleLabelFour.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dashboardTitleLabelFour.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTitleLabelFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardTitleLabelFour.setText("Close Application");

        javax.swing.GroupLayout dashboardTitlePanelFourLayout = new javax.swing.GroupLayout(dashboardTitlePanelFour);
        dashboardTitlePanelFour.setLayout(dashboardTitlePanelFourLayout);
        dashboardTitlePanelFourLayout.setHorizontalGroup(
            dashboardTitlePanelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLabelFour, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );
        dashboardTitlePanelFourLayout.setVerticalGroup(
            dashboardTitlePanelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTitlePanelFourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardTitleLabelFour, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        applicationCloseButton.setBackground(new java.awt.Color(233, 28, 76));
        applicationCloseButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        applicationCloseButton.setForeground(new java.awt.Color(255, 255, 255));
        applicationCloseButton.setText("Close");
        applicationCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardFourLayout = new javax.swing.GroupLayout(dashboardFour);
        dashboardFour.setLayout(dashboardFourLayout);
        dashboardFourLayout.setHorizontalGroup(
            dashboardFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitlePanelFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardFourLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applicationCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        dashboardFourLayout.setVerticalGroup(
            dashboardFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardFourLayout.createSequentialGroup()
                .addComponent(dashboardTitlePanelFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applicationCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        dashboardThree.setBackground(new java.awt.Color(32, 26, 49));

        dashboardTitlePanelThree.setBackground(new java.awt.Color(98, 76, 249));

        dashboardTitleLabelThree.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dashboardTitleLabelThree.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTitleLabelThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardTitleLabelThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/search.png"))); // NOI18N
        dashboardTitleLabelThree.setText("Search By Hospital Category");

        javax.swing.GroupLayout dashboardTitlePanelThreeLayout = new javax.swing.GroupLayout(dashboardTitlePanelThree);
        dashboardTitlePanelThree.setLayout(dashboardTitlePanelThreeLayout);
        dashboardTitlePanelThreeLayout.setHorizontalGroup(
            dashboardTitlePanelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLabelThree, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        dashboardTitlePanelThreeLayout.setVerticalGroup(
            dashboardTitlePanelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTitlePanelThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardTitleLabelThree, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        searchByGovernment.setBackground(new java.awt.Color(32, 26, 49));
        searchByHospitalCategoryButtonGroup.add(searchByGovernment);
        searchByGovernment.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        searchByGovernment.setForeground(new java.awt.Color(255, 255, 255));
        searchByGovernment.setText("Government");

        searchByPrivate.setBackground(new java.awt.Color(32, 26, 49));
        searchByHospitalCategoryButtonGroup.add(searchByPrivate);
        searchByPrivate.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        searchByPrivate.setForeground(new java.awt.Color(255, 255, 255));
        searchByPrivate.setText("Private");

        searchByCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/go.png"))); // NOI18N
        searchByCategoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByCategoryButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashboardThreeLayout = new javax.swing.GroupLayout(dashboardThree);
        dashboardThree.setLayout(dashboardThreeLayout);
        dashboardThreeLayout.setHorizontalGroup(
            dashboardThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitlePanelThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dashboardThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchByGovernment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchByPrivate)
                .addGap(24, 24, 24))
            .addGroup(dashboardThreeLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(searchByCategoryButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardThreeLayout.setVerticalGroup(
            dashboardThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardThreeLayout.createSequentialGroup()
                .addComponent(dashboardTitlePanelThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dashboardThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByGovernment)
                    .addComponent(searchByPrivate))
                .addGap(18, 18, 18)
                .addComponent(searchByCategoryButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        searchByNameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/go.png"))); // NOI18N
        searchByNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByNameButtonMouseClicked(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(102, 255, 102));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/calender.png"))); // NOI18N

        timeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/clock.png"))); // NOI18N
        timeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchIconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchByHospitalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchByNameButton)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(timeLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dashboardThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dashboardOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dashboardFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dashboardTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(55, 55, 55))))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(searchIconLabel)
                        .addComponent(searchByHospitalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchByNameButton)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homePageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageLabelMouseEntered
        homePageLabel.setBackground(new Color(56,48,76)); 
    }//GEN-LAST:event_homePageLabelMouseEntered

    private void formPageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formPageLabelMouseEntered
        formPageLabel.setBackground(new Color(56, 48, 76));
    }//GEN-LAST:event_formPageLabelMouseEntered

    private void tablePageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePageLabelMouseEntered
        tablePageLabel.setBackground(new Color(56, 48, 76));
    }//GEN-LAST:event_tablePageLabelMouseEntered

    private void aboutUsPageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsPageLabelMouseEntered
        aboutUsPageLabel.setBackground(new Color(56, 48, 76));
    }//GEN-LAST:event_aboutUsPageLabelMouseEntered

    private void homePageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageLabelMouseExited
        homePageLabel.setBackground(new Color(32, 26, 49)); 
    }//GEN-LAST:event_homePageLabelMouseExited

    private void formPageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formPageLabelMouseExited
        formPageLabel.setBackground(new Color(32, 26, 49));
    }//GEN-LAST:event_formPageLabelMouseExited

    private void tablePageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePageLabelMouseExited
        tablePageLabel.setBackground(new Color(32, 26, 49));
    }//GEN-LAST:event_tablePageLabelMouseExited

    private void aboutUsPageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsPageLabelMouseExited
        aboutUsPageLabel.setBackground(new Color(32, 26, 49));
    }//GEN-LAST:event_aboutUsPageLabelMouseExited

    private void homePageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageLabelMouseClicked
        // Nothings happens as we are already in home page
    }//GEN-LAST:event_homePageLabelMouseClicked

    private void formPageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formPageLabelMouseClicked
        this.setVisible(false); 
        formPage.setVisible(true); 
    }//GEN-LAST:event_formPageLabelMouseClicked

    private void tablePageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePageLabelMouseClicked
        this.setVisible(false); 
        tablePage.setVisible(true);
    }//GEN-LAST:event_tablePageLabelMouseClicked

    private void aboutUsPageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsPageLabelMouseClicked
        this.setVisible(false); 
        aboutUsPage.setVisible(true); 
    }//GEN-LAST:event_aboutUsPageLabelMouseClicked

    private void logOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseClicked
        LogoutDialogBox logoutDialogBox = new LogoutDialogBox(this, true);
        logoutDialogBox.setVisible(true);
        if(logoutDialogBox.isLogout()) {
            this.dispose();
            new LoginPage().setVisible(true); 
        }
    }//GEN-LAST:event_logOutLabelMouseClicked

    private void logOutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseEntered
        logOutLabel.setBackground(new Color(56,48,76));
    }//GEN-LAST:event_logOutLabelMouseEntered

    private void logOutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseExited
        logOutLabel.setBackground(new Color(32, 26, 49));
    }//GEN-LAST:event_logOutLabelMouseExited

    private void searchByNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByNameButtonMouseClicked
        String hospitalName = searchByHospitalNameField.getText().trim();
        SelectionSort.nameBasedSelectionSort(tablePage.getHospitalDatas()); 
        addSortedData();
        if (hospitalName.isEmpty()) { 
            new MessageDialogBox(this, "Please enter hospital name", true).setVisible(true);
        }else {
            int index = BinarySearch.hospitalNameBinarySearch(tablePage.getHospitalDatas(), hospitalName);
            if (index == -1) {
                    new MessageDialogBox(this, "No any hospital data found", true).setVisible(true);
            }else {
                String message = getHospitalSearchInformationAtIndex(index); 
                JOptionPane.showMessageDialog(this, message); 
            }
        }
    }//GEN-LAST:event_searchByNameButtonMouseClicked

    private void searchByPriceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByPriceButtonMouseClicked
        String priceInString = searchByPriceField.getText().trim();
        SelectionSort.priceBasedSelectionSort(tablePage.getHospitalDatas());
        addSortedData();
        try {
            double price = Double.parseDouble(priceInString);
            int index = BinarySearch.admittedPriceBinarySearch(tablePage.getHospitalDatas(), price);
            if (index == -1) {
                new MessageDialogBox(this, "No any hospital data found", true).setVisible(true);
            }else {
                String message = getHospitalSearchInformationAtIndex(index);
                JOptionPane.showMessageDialog(this, message);
            }
        }catch(NumberFormatException numberFormatException) {
            new MessageDialogBox(this, "Please enter price in numeric form", true).setVisible(true); 
        }
    }//GEN-LAST:event_searchByPriceButtonMouseClicked

    private void searchByCategoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByCategoryButtonMouseClicked
        String hospitalCategory = "";
        if (searchByGovernment.isSelected())
            hospitalCategory = "Government";
        else if (searchByPrivate.isSelected())
            hospitalCategory = "Private"; 
        
        if (hospitalCategory.isEmpty()) {
            new MessageDialogBox(this, "Please select at least one category", true).setVisible(true);  
        }else {
            SelectionSort.categoryBasedSelectionSort(tablePage.getHospitalDatas()); 
            addSortedData();
            boolean found = false;
            String message = "The hospital names with " + hospitalCategory + " category:-\n";
            for(int i = 0; i < tablePage.getHospitalDatas().size(); i++) {
                if(tablePage.getHospitalDatas().get(i).getHospitalCategory().equals(hospitalCategory)) {
                    found = true;
                    message += tablePage.getHospitalDatas().get(i).getHospitalName() + "\n";
                } 
            }
            if(!found) 
                new MessageDialogBox(this, "No any hospital data found", true).setVisible(true);
            else {
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_searchByCategoryButtonMouseClicked

    private void applicationCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationCloseButtonActionPerformed
        new ExitingDialogBox(this, true).setVisible(true); 
    }//GEN-LAST:event_applicationCloseButtonActionPerformed

    private void searchByHospitalNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByHospitalNameFieldMouseClicked
        String hospitalName = searchByHospitalNameField.getText().trim();
        if (hospitalName.equals("Search"))
            searchByHospitalNameField.setText(""); 
    }//GEN-LAST:event_searchByHospitalNameFieldMouseClicked

    private void searchByPriceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchByPriceFieldKeyTyped
        enableTypingNumberKeyOnly(evt); 
    }//GEN-LAST:event_searchByPriceFieldKeyTyped

    private void timeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeLabelMouseClicked
        time =  timeFormat.format(Calendar.getInstance().getTime());
        new MessageDialogBox(this, "The current time is: " + time, true).setVisible(true); 
    }//GEN-LAST:event_timeLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new LoginPage().setVisible(true); 
                new HospitalInfo().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUsPageLabel;
    private javax.swing.JButton applicationCloseButton;
    private javax.swing.JPanel dashboardFour;
    private javax.swing.JPanel dashboardOne;
    private javax.swing.JPanel dashboardThree;
    private javax.swing.JLabel dashboardTitleLabelFour;
    private javax.swing.JLabel dashboardTitleLabelOne;
    private javax.swing.JLabel dashboardTitleLabelThree;
    private javax.swing.JLabel dashboardTitleLabelTwo;
    private javax.swing.JPanel dashboardTitlePanelFour;
    private javax.swing.JPanel dashboardTitlePanelOne;
    private javax.swing.JPanel dashboardTitlePanelThree;
    private javax.swing.JPanel dashboardTitlePanelTwo;
    private javax.swing.JPanel dashboardTwo;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel formPageLabel;
    private javax.swing.JLabel homePageLabel;
    private javax.swing.JLabel hospitalNumberLabel;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel rupeesLabel;
    private javax.swing.JLabel searchByCategoryButton;
    private javax.swing.JRadioButton searchByGovernment;
    private javax.swing.ButtonGroup searchByHospitalCategoryButtonGroup;
    private javax.swing.JTextField searchByHospitalNameField;
    private javax.swing.JLabel searchByNameButton;
    private javax.swing.JLabel searchByPriceButton;
    private javax.swing.JTextField searchByPriceField;
    private javax.swing.JRadioButton searchByPrivate;
    private javax.swing.JLabel searchIconLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel tablePageLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
