/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital_is;

import com.dialogs.MessageDialogBox;
import com.dialogs.ExitingDialogBox;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author abc
 */
public class LoginPage extends javax.swing.JFrame {
    private HospitalInfo hospitalInfo;
    private final String USER_NAME = "admin";
    private final String PASSWORD = "password";
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        ImageIcon bgImage = resizePhoto("src/com/icons/loginImage.png");
        backgroundImageLabel.setIcon(bgImage); 
        hospitalInfo = new HospitalInfo(); 
        ImageIcon applicationIcon = new ImageIcon("src/com/icons/application_hospital_icon.png");
        this.setIconImage(applicationIcon.getImage()); 
    }

    public HospitalInfo getHospitalInfo() {
        return hospitalInfo;
    }
    
    public ImageIcon resizePhoto(String imageUrl) {
        ImageIcon icon = new ImageIcon(imageUrl);
        Image scaledImage = icon.getImage().getScaledInstance(this.getWidth(), 162, Image.SCALE_DEFAULT);
        ImageIcon newScaledImage = new ImageIcon(scaledImage);
        return newScaledImage;
    }
   
    public void changeLoginPageBackgroundColorLight() {
        mainPanel.setBackground(Color.white);
        userNameTextField.setBackground(new Color(245, 245, 245));
        passwordTextField.setBackground(new Color(245, 245, 245));
    }
    
    public void changeLoginPageBackgroundColorDark() {
        mainPanel.setBackground(new Color(32,26,49));
        userNameTextField.setBackground(new Color(56,48,76));
        passwordTextField.setBackground(new Color(56,48,76)); 
    }
    
    public void changeLoginPageForegroundColorDark() {
        headingLabel.setForeground(Color.black);
        subHeadingLabel.setForeground(Color.black);
        userNameTextField.setForeground(Color.black);
        passwordTextField.setForeground(Color.black); 
    }
    
    public void changeLoginPageForegroundColorLight() {
        headingLabel.setForeground(Color.white);
        subHeadingLabel.setForeground(Color.white);
        userNameTextField.setForeground(Color.white);
        passwordTextField.setForeground(Color.white);
    }
    
    public void changeLightAndDarkMode() {
        ImageIcon darkIcon = new ImageIcon("src/com/icons/dark.png");
        ImageIcon lightIcon = new ImageIcon("src/com/icons/light.png"); 
        
        if (backgroundChangerLabel.getIcon().toString().equals("src/com/icons/light.png")) {   
            backgroundChangerLabel.setIcon(darkIcon);
            changeLoginPageForegroundColorDark();
            changeLoginPageBackgroundColorLight();
        }else {   
            backgroundChangerLabel.setIcon(lightIcon); 
            changeLoginPageForegroundColorLight(); 
            changeLoginPageBackgroundColorDark();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        subHeadingLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        backgroundChangerLabel = new javax.swing.JLabel();
        headingSubheadingSeparator = new javax.swing.JSeparator();
        backgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(32, 26, 49));

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/quit.png"))); // NOI18N
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("Login");

        subHeadingLabel.setBackground(new java.awt.Color(204, 204, 204));
        subHeadingLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        subHeadingLabel.setForeground(new java.awt.Color(204, 204, 204));
        subHeadingLabel.setText("Please Sign In to Continue");

        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/password.png"))); // NOI18N

        userNameTextField.setBackground(new java.awt.Color(56, 48, 76));
        userNameTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        userNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        userNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/user.png"))); // NOI18N

        passwordTextField.setBackground(new java.awt.Color(56, 48, 76));
        passwordTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(255, 255, 255));
        passwordTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        loginButton.setBackground(new java.awt.Color(13, 245, 227));
        loginButton.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        loginButton.setText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginButton.setOpaque(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        backgroundChangerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/light.png"))); // NOI18N
        backgroundChangerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundChangerLabelMouseClicked(evt);
            }
        });

        backgroundImageLabel.setBackground(new java.awt.Color(0, 0, 0));
        backgroundImageLabel.setOpaque(true);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordTextField))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(headingSubheadingSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backgroundChangerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(subHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(exitLabel)
                        .addContainerGap())))
            .addComponent(backgroundImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(backgroundImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(headingSubheadingSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backgroundChangerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(46, 46, 46)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        new ExitingDialogBox(this, true).setVisible(true); 
    }//GEN-LAST:event_exitLabelMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String userName = userNameTextField.getText().trim();
        String password = String.valueOf(passwordTextField.getPassword()).trim();

        if (userName.isEmpty() && password.isEmpty()) {
            new MessageDialogBox(this, "Please enter username and password", true).setVisible(true);
        }else if (!userName.equals(USER_NAME) || !password.equals(PASSWORD)) {
            new MessageDialogBox(this, "user name and Password didn't match", true).setVisible(true); 
        }else if (userName.equals(USER_NAME) && password.equals(PASSWORD)) {
            this.setVisible(false);
            hospitalInfo.setVisible(true);
        }  
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backgroundChangerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundChangerLabelMouseClicked
        changeLightAndDarkMode(); 
    }//GEN-LAST:event_backgroundChangerLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundChangerLabel;
    private javax.swing.JLabel backgroundImageLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JSeparator headingSubheadingSeparator;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel subHeadingLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
