/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital_is;

import com.algorithms.SelectionSort;
import com.dialogs.ExitingDialogBox;
import com.dialogs.MessageDialogBox;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abc
 */
public class TablePage extends javax.swing.JFrame {
    private HospitalInfo hospitalInfo;
    private ArrayList<HospitalData> hospitalDatas;
    
    /**
     * Creates new form TablePage
     */
    public TablePage(HospitalInfo hospitalInfo) {
        initComponents();
        hospitalInfoTable.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 18));
        this.hospitalInfo = hospitalInfo;
        hospitalDatas = new ArrayList<HospitalData>();
        ImageIcon applicationIcon = new ImageIcon("src/com/icons/application_hospital_icon.png");
        this.setIconImage(applicationIcon.getImage()); 
    }

    public ArrayList<HospitalData> getHospitalDatas() {
        return hospitalDatas;
    }
    
    public JTable getHospitalInfoTable() {
        return hospitalInfoTable;
    }
    
    public void openFile() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Please Select a file to load into a table"); 
        int option = fileChooser.showOpenDialog(this); 
        if (option == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + filePath);
           }catch(Exception exception) {
               System.err.println(exception);
           }
        }
    }
    
    public void saveDataToCsvFile() {
        File file = new File("src/com/data/hospital_information.csv");
        try {
        FileWriter fileWriter = new FileWriter(file);
        for (HospitalData data : hospitalDatas) {
            String value[] = {data.getHospitalName(), data.getAddress(), String.valueOf(data.getTelephoneNumber()), 
                data.getHospitalCategory(), String.valueOf(data.getAdmittedPrice()), data.getHealthInsurence()};
            for (int i = 0; i < value.length; i++) {
                fileWriter.append(value[i]);
                if (i == value.length - 1) {
                    break;
                }
                fileWriter.append(",");
            }
            fileWriter.append("\n");
        }
        fileWriter.flush();
        fileWriter.close();
        }catch(IOException exception) {
            new MessageDialogBox(this, "Input/Outpur Exception Found", true).setVisible(true); 
        }
    }
    
    public void loadCsvFile() {
        File file = new File("src/com/data/hospital_information.csv");
        try {
            FileReader fileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(fileReader); 
            String row = "";
            while ((row = bufferedReader.readLine()) != null) {  
                String values[] = row.split(",");
                HospitalData hospitalData = new HospitalData(values[0], values[1], values[2], values[3], values[4], values[5]);
                hospitalDatas.add(hospitalData);
                DefaultTableModel tableModel = (DefaultTableModel) hospitalInfoTable.getModel();
                tableModel.addRow(values); 
            }
        }catch(FileNotFoundException fileNotFoundException) {
            new MessageDialogBox(this, "File not Found. Please Check the file structure", true).setVisible(true); 
        }catch(IOException iOException) {
            new MessageDialogBox(this, "Input/Output Exception Occured", true).setVisible(true);
        }
    }
    
    public void openHelpFile() {
        try {
            File filePath = new File("src/com/data/help_file.pdf");
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + filePath);
        }catch(IOException exception) {
            new MessageDialogBox(this, "File Protocol Handler Exception Occured", true).setVisible(true); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tableHeadingLabel = new javax.swing.JLabel();
        homePageBackLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hospitalInfoTable = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        loadCsvFile = new javax.swing.JMenuItem();
        exitApplication = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        developerMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(32, 26, 49));

        tableHeadingLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        tableHeadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        tableHeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableHeadingLabel.setText("Hospital Information System");

        homePageBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/home_back.png"))); // NOI18N
        homePageBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePageBackLabelMouseClicked(evt);
            }
        });

        hospitalInfoTable.setBackground(new java.awt.Color(232, 232, 232));
        hospitalInfoTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hospitalInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Address", "Telephone Number", "Hospital Category", "Admitted Price", "Health Insurance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hospitalInfoTable.setGridColor(new java.awt.Color(255, 255, 255));
        hospitalInfoTable.setRowHeight(36);
        jScrollPane2.setViewportView(hospitalInfoTable);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(homePageBackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(tableHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addComponent(jScrollPane2)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(homePageBackLabel)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
        );

        jMenuBar2.setPreferredSize(new java.awt.Dimension(66, 46));

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        fileMenu.setPreferredSize(new java.awt.Dimension(59, 24));

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/menubar_open.png"))); // NOI18N
        openFile.setText("Open File");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        fileMenu.add(openFile);

        loadCsvFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadCsvFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/menubar_load.png"))); // NOI18N
        loadCsvFile.setText("Load CSV File");
        loadCsvFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCsvFileActionPerformed(evt);
            }
        });
        fileMenu.add(loadCsvFile);

        exitApplication.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/menubar_exit.png"))); // NOI18N
        exitApplication.setText("Exit");
        exitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApplicationActionPerformed(evt);
            }
        });
        fileMenu.add(exitApplication);

        jMenuBar2.add(fileMenu);

        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        helpMenu.setPreferredSize(new java.awt.Dimension(69, 24));
        helpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(helpMenu);

        developerMenu.setText("Developer");
        developerMenu.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        developerMenu.setPreferredSize(new java.awt.Dimension(121, 24));
        developerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                developerMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(developerMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homePageBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageBackLabelMouseClicked
        hospitalInfo.getHospitalNumberLabel().setText(String.valueOf(hospitalDatas.size()));  
        this.setVisible(false); 
        hospitalInfo.setVisible(true); 
    }//GEN-LAST:event_homePageBackLabelMouseClicked

    private void loadCsvFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCsvFileActionPerformed
        loadCsvFile();
    }//GEN-LAST:event_loadCsvFileActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        openFile();
    }//GEN-LAST:event_openFileActionPerformed

    private void exitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApplicationActionPerformed
        new ExitingDialogBox(this, true).setVisible(true); 
    }//GEN-LAST:event_exitApplicationActionPerformed

    private void helpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuMouseClicked
       openHelpFile();
    }//GEN-LAST:event_helpMenuMouseClicked

    private void developerMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_developerMenuMouseClicked
        this.setVisible(false);
        hospitalInfo.getAboutUsPage().setVisible(true); 
    }//GEN-LAST:event_developerMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablePage(new HospitalInfo()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu developerMenu;
    private javax.swing.JMenuItem exitApplication;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel homePageBackLabel;
    private javax.swing.JTable hospitalInfoTable;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadCsvFile;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JLabel tableHeadingLabel;
    // End of variables declaration//GEN-END:variables
}
