/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dialogs;

/**
 *
 * @author abc
 */
public class UserConfirmationDialogBox extends javax.swing.JDialog {
    private static String confirmationMessage;
    private boolean confirm;
    
    /**
     * Creates new form UserConfirmationDialogBox
     */
    public UserConfirmationDialogBox(java.awt.Frame parent, String confirmationMessage ,boolean modal) {
        super(parent, modal);
        initComponents();
        this.confirmationMessage = confirmationMessage;
        confirmationMessageLabel.setText(confirmationMessage); 
        this.confirm = false;
    }

    public boolean isConfirm() {
        return confirm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        exitIconLabel = new javax.swing.JLabel();
        confirmationMessageLabel = new javax.swing.JLabel();
        noLabel = new javax.swing.JLabel();
        yeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(56, 48, 76));
        mainPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(255, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(255, 51, 51)));

        exitIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/choose.png"))); // NOI18N

        confirmationMessageLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        confirmationMessageLabel.setForeground(new java.awt.Color(255, 255, 255));
        confirmationMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        noLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        noLabel.setForeground(new java.awt.Color(255, 255, 255));
        noLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/no.png"))); // NOI18N
        noLabel.setText("No");
        noLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noLabelMouseClicked(evt);
            }
        });

        yeLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        yeLabel.setForeground(new java.awt.Color(255, 255, 255));
        yeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/yes.png"))); // NOI18N
        yeLabel.setText("Yes");
        yeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmationMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(exitIconLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(yeLabel)
                .addGap(71, 71, 71)
                .addComponent(noLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmationMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yeLabelMouseClicked
        confirm = true;
        this.dispose();
    }//GEN-LAST:event_yeLabelMouseClicked

    private void noLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noLabelMouseClicked
        confirm = false;
        this.dispose();
    }//GEN-LAST:event_noLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserConfirmationDialogBox dialog = new UserConfirmationDialogBox(new javax.swing.JFrame(), confirmationMessage, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmationMessageLabel;
    private javax.swing.JLabel exitIconLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel noLabel;
    private javax.swing.JLabel yeLabel;
    // End of variables declaration//GEN-END:variables
}
